services:
  frontend:
    image: itsanindyak/todo-app:latest
    container_name: todo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
